apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-stateful
spec:
  selector:
    matchLabels:
      app: nginx-stateful
  serviceName: "nginx-stateful"
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-stateful
    spec:
      containers:
        - name: webserver
          image: nginx:latest
          ports:
            - containerPort: 80
              name: web